---
title: "CodeBook"
author: "Alejandro Erasso"
date: "Sunday, May 24, 2015"
output: html_document
---

The experiments have been carried out with a group of 30 volunteers within an age bracket of 19-48 years. Each person performed six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) on the waist. Using its embedded accelerometer and gyroscope, we captured 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz. The experiments have been video-recorded to label the data manually. The obtained dataset has been randomly partitioned into two sets, where 70% of the volunteers was selected for generating the training data and 30% the test data. 

The sensor signals (accelerometer and gyroscope) were pre-processed by applying noise filters and then sampled in fixed-width sliding windows of 2.56 sec and 50% overlap (128 readings/window). The sensor acceleration signal, which has gravitational and body motion components, was separated using a Butterworth low-pass filter into body acceleration and gravity. The gravitational force is assumed to have only low frequency components, therefore a filter with 0.3 Hz cutoff frequency was used. From each window, a vector of features was obtained by calculating variables from the time and frequency domain. See 'features_info.txt' for more details. 

---
The dataset includes the following fields for each record:

Subject: Numerical identifier of each of the subjects to the experiment,

-    1
-    2
-    3
-    ...
-    30

ActivityName: One of the six possible activities (strings) performed by each Subject,

-    LAYING
-    SITTING
-    STANDING
-    WALKING
-    WALKING_DOWNSTAIRS
-    WALKING_UPSTAIRS

Times of multiple measurements, as mean value (real) of total observations for each Subject and ActivityName:

For body acceleration

-       tBodyAcc-mean()-X
        
-       tBodyAcc-mean()-Y
        
-        tBodyAcc-mean()-Z
        
-        tBodyAcc-std()-X
        
-        tBodyAcc-std()-Y
        
-        tBodyAcc-std()-Z

For gravitational acceleration

-       tGravityAcc-mean()-X

-       tGravityAcc-mean()-Y

-       tGravityAcc-mean()-Z

-       tGravityAcc-std()-X

-       tGravityAcc-std()-Y

-        tGravityAcc-std()-Z

For jerk movement of body acceleration

-       tBodyAccJerk-mean()-X

-       tBodyAccJerk-mean()-Y

-       tBodyAccJerk-mean()-Z

-       tBodyAccJerk-std()-X

-       tBodyAccJerk-std()-Y

-       tBodyAccJerk-std()-Z

For gyroscopic body acceleration

-        tBodyGyro-mean()-X
        
-        tBodyGyro-mean()-Y
        
-        tBodyGyro-mean()-Z
        
-        tBodyGyro-std()-X
        
-        tBodyGyro-std()-Y
        
-        tBodyGyro-std()-Z
    
For jerk movement of gyroscopic body acceleration

-        tBodyGyroJerk-mean()-X
                
-        tBodyGyroJerk-mean()-Y
        
-        tBodyGyroJerk-mean()-Z
        
-        tBodyGyroJerk-std()-X
        
-        tBodyGyroJerk-std()-Y
        
-        tBodyGyroJerk-std()-Z
        
-        tBodyAccMag-mean()
        
-        tBodyAccMag-std()
    
For magnitude of gravitational acceleration

-        tGravityAccMag-mean()
        
-        tGravityAccMag-std()
    
For magnitude of jerk movement of body acceleration

-        tBodyAccJerkMag-mean()
        
-        tBodyAccJerkMag-std()
    
For magnitude of gyroscopic body acceleration

-        tBodyGyroMag-mean()
    
-        tBodyGyroMag-std()
        
For magnitude of jerk movement of gyroscopic body acceleration
        
-        tBodyGyroJerkMag-mean()
        
-        tBodyGyroJerkMag-std()
        
---

Frequency of multiple measurements, as mean value (real) of total observations:
    
For body acceleration

-        fBodyAcc-mean()-X
        
-        fBodyAcc-mean()-Y
        
-        fBodyAcc-mean()-Z
        
-        fBodyAcc-std()-X
        
-        fBodyAcc-std()-Y
        
-        fBodyAcc-std()-Z
        
-        fBodyAcc-meanFreq()-X
        
-        fBodyAcc-meanFreq()-Y
        
-        fBodyAcc-meanFreq()-Z
    
For jerk movement of body acceleration

-        fBodyAccJerk-mean()-X
        
-        fBodyAccJerk-mean()-Y
        
-        fBodyAccJerk-mean()-Z
        
-        fBodyAccJerk-std()-X
        
-        fBodyAccJerk-std()-Y
        
-        fBodyAccJerk-std()-Z
        
-        fBodyAccJerk-meanFreq()-X
        
-        fBodyAccJerk-meanFreq()-Y
        
-        fBodyAccJerk-meanFreq()-Z
    
For gyroscopic body acceleration 

-        fBodyGyro-mean()-X
        
-        fBodyGyro-mean()-Y
    
-        fBodyGyro-mean()-Z
        
-        fBodyGyro-std()-X
        
-        fBodyGyro-std()-Y
        
-        fBodyGyro-std()-Z
        
-        fBodyGyro-meanFreq()-X
        
-        fBodyGyro-meanFreq()-Y
        
-        fBodyGyro-meanFreq()-Z
    
For magnitude of body acceleration

-        fBodyAccMag-mean()
        
-        fBodyAccMag-std()
        
-        fBodyAccMag-meanFreq()
    
For magnitude of jerk movement of body acceleration

-        fBodyBodyAccJerkMag-mean()
        
-        fBodyBodyAccJerkMag-std()
        
-        fBodyBodyAccJerkMag-meanFreq()
    
For magnitude of gyroscopic body acceleration
    
-        fBodyBodyGyroMag-mean()
        
-        fBodyBodyGyroMag-std()

-        fBodyBodyGyroMag-meanFreq()
  
For magnitude of jerk movement of gyroscopic body acceleration
        
-        fBodyBodyGyroJerkMag-mean()
        
-        fBodyBodyGyroJerkMag-std()
        
-        fBodyBodyGyroJerkMag-meanFreq()
        
---
        